"""add phone number number column to posts table

Revision ID: 1e4809a59ee1
Revises: 73b25e30ab56
Create Date: 2022-01-25 20:11:11.184408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4809a59ee1'
down_revision = '73b25e30ab56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
