"""add post_code to posts table

Revision ID: a8b328605570
Revises: 75bfe64276da
Create Date: 2022-01-25 21:30:48.792977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b328605570'
down_revision = '75bfe64276da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_code')
    # ### end Alembic commands ###
